export const ALPHABET = [
  {
    id: 1,
    english: "person",
    spanish: "persona",
    native: "Achi",
  },
  {
    id: 2,
    english: "bicycle",
    spanish: "bicicleta",
    native: "B'siklet",
  },
  {
    id: 3,
    english: "car",
    spanish: "carro",
    native: "Chi'ich' reb'al jastaq",
  },
  {
    id: 4,
    english: "motorcycle",
    spanish: "motocicleta",
    native: "Mot",
  },
  {
    id: 5,
    english: "airplane",
    spanish: "avion",
    native: "Ch'ich' kab'in pa kaj",
  },
  {
    id: 6,
    english: "bus",
    spanish: "bus",
    native: "Chi'ich' ereb'al winaq",
  },
  {
    id: 7,
    english: "train",
    spanish: "tren",
    native: "Yuquyik ch'ich'",
  },
  {
    id: 9,
    english: "boat",
    spanish: "bote",
    native: "Nim jukub'",
  },
  {
    id: 13,
    english: "stop sign",
    spanish: "señal de transito",
    native: "K’ulb’a’t",
  },
  {
    id: 15,
    english: "bench",
    spanish: "silla, trono, banca",
    native: "Tem",
  },
  {
    id: 16,
    english: "bird",
    spanish: "pájaro",
    native: "tzʼikin",
  },
  {
    id: 17,
    english: "cat",
    spanish: "gato",
    native: "Me’s",
  },
  {
    id: 18,
    english: "dog",
    spanish: "perro",
    native: "Tz’i’",
  },
  {
    id: 19,
    english: "horse",
    spanish: "caballo",
    native: "Kej",
  },
  {
    id: 20,
    english: "sheep",
    spanish: "oveja",
    native: "Karne'l",
  },
  {
    id: 21,
    english: "cow",
    spanish: "vaca",
    native: "Wakax",
  },
  {
    id: 27,
    english: "backpack",
    spanish: "bolso",
    native: "umoral",
  },
  {
    id: 31,
    english: "handbag",
    spanish: "mochila",
    native: "umoral",
  },
  {
    id: 47,
    english: "cup",
    spanish: "taza",
    native: "Xaru’",
  },
  {
    id: 48,
    english: "fork",
    spanish: "tenedor",
    native: "Ixk’yaq",
  },
  {
    id: 49,
    english: "knife",
    spanish: "cuchillo",
    native: "Q’atb’al || Pilb’al",
  },
  {
    id: 50,
    english: "spoon",
    spanish: "cuchara",
    native: "Pak'",
  },
  {
    id: 51,
    english: "bowl",
    spanish: "recipiente",
    native: "Tol",
  },
  {
    id: 52,
    english: "banana",
    spanish: "banano",
    native: "Ankane'y",
  },
  {
    id: 53,
    english: "apple",
    spanish: "manzana",
    native: "Mansa'n",
  },
  {
    id: 55,
    english: "orange",
    spanish: "naranja",
    native: "Alanxax",
  },
  {
    id: 62,
    english: "chair",
    spanish: "silla",
    native: "Tem",
  },
  {
    id: 63,
    english: "couch",
    spanish: "sillon",
    native: "Nimatem",
  },
  {
    id: 65,
    english: "bed",
    spanish: "cama",
    native: "Ch'at",
  },
  {
    id: 67,
    english: "dining table",
    spanish: "mesa de centro",
    native: "Mexa",
  },
  {
    id: 70,
    english: "toilet",
    spanish: "sanitario",
    native: "B'alb'al chuluj",
  },
  {
    id: 72,
    english: "tv",
    spanish: "television",
    native: "ka'yib'al wachib'al",
  },
  {
    id: 73,
    english: "laptop",
    spanish: "computadora",
    native: "Kematz'ib' ",
  },
  {
    id: 74,
    english: "mouse",
    spanish: "raton",
    native: "Ch'o",
  },
  {
    id: 77,
    english: "cell phone",
    spanish: "telefono",
    native: "Ch'ab'eb'al",
  },
  {
    id: 84,
    english: "book",
    spanish: "libro",
    native: "Wuj",
  },
  {
    id: 87,
    english: "scissors",
    spanish: "tijeras",
    native: "Tuxe'r",
  },
  {
    id: 88,
    english: "telephone",
    spanish: "telefono",
    native: "Ch'ab'eb'al",
  },
  {
    id: 91,
    english: "house",
    spanish: "casa",
    native: "Achoch",
  },
  {
    id: 92,
    english: "tree",
    spanish: "arbol",
    native: "che'",
  },
]
